version: '3.8'

services:
  client:
   build: ./front
   container_name: client_frontend
   ports:
   - '3001:3001'
   volumes:
   - .:/app
   stdin_open: true
   tty: true
     
  backend:
   build: ./back
   container_name: client_backend
   ports:
   - "8002:80"
   volumes:
   - .:/app
