version: '3.8'

services:
  client:
   build: ./front
   container_name: client_frontend_2
   ports:
   - '3001:3001'
   volumes:
   - .:/app
   stdin_open: true
   tty: true
     
  backend:
   build: ./back
   container_name: client_backend_2
   ports:
   - "${BACKEND_PORT}:80"
   volumes:
   - .:/app
